name: Security Scanning

on:
  push:
    branches: [ main ]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ZAP Security Scan
        uses: zaproxy/action-baseline@v1
        with:
          target: "https://thinking-tester-contact-list.herokuapp.com"
          output: "security_scan_report.html"
