name: Check run

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - run: sudo apt-get update && sudo apt-get install -y nginx && sudo systemctl start nginx

    - name: ZAP Scan
      uses: ./
      id: action-baseline
      with:
        target: '"https://thinking-tester-contact-list.herokuapp.com"

        allow_issue_writing: false
        
         
          
              
            
