name: Security Scanning

on:
  push:
    branches: [main]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
          target: "https://thinking-tester-contact-list.herokuapp.com"
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
          
              
            
