name: End-to-end tests

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci  # Use npm ci for a clean install
        
      - name: Build project
        run: npm run build  # Ensure your project is built before running tests

      - name: Start server
        run: npm start &
        
      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.1.1
        with:
          timeout: '60'  # Wait for 60 seconds
          url: 'http://localhost:3000'  # Adjust to your server's URL

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.json  # Ensure you have the correct config file
      



