name: Automated Tests and Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress_tests:
    name: Cypress UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run Cypress Tests
        run: npm run cy:run

  security_tests:
    name: Security Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install ZAP
        uses: zaproxy/action-full-scan@v0.9.2
        with:
          target: https://example.com
          policies: https://raw.githubusercontent.com/zaproxy/community-scripts/main/policy/Example_policy.xml
          enablepassive: true
      # Add more security testing steps as needed

  api_tests:
    name: API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run API Tests
        run: npm run api:test

