on: [push]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # Update to match your default branch
      # Debugging step to check the git status
      - name: Check git status
        run: git status
      # Ensure we have the latest commit and branch information
      - name: Fetch all branches
        run: git fetch --all
      # Check if the correct branch is checked out
      - name: Verify branch
        run: git branch -v
      # Debugging step to list the contents of the repository
      - name: List files
        run: ls -la
      # Debugging step to ensure .zap/rules.tsv exists
      - name: Check ZAP rules file
        run: cat .zap/rules.tsv
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
